### ISSUE TITLE
Error when executing tool

### ISSUE THREAD

**Issue by ryanjshields** [juliepierson/DissolveWithStats#9]
Receive the following error while executing the tool. The dissolve geometry portion is functional but none of my fields (string nor numerical) summarized in the output.

TypeError: sequence item 0: expected str instance, QVariant found 
Traceback (most recent call last):
  File "/Users/ryanshields/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DissolveWithStats/dissolve_stats.py", line 219, in run
    dicNewValues = self.calculateFields(selectedLayer, selectedField, listKeep, listStats, outFile)
  File "/Users/ryanshields/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DissolveWithStats/dissolve_stats.py", line 254, in calculateFields
    newValues = self.aggregateValues(listStats[i], dicNewValues[k][field])
  File "/Users/ryanshields/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DissolveWithStats/dissolve_stats.py", line 274, in aggregateValues
    return switcher[stat](l)
  File "/Users/ryanshields/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DissolveWithStats/dissolve_stats.py", line 262, in 
    "Concatenation": lambda l: ",".join(l) if l else NULL,
TypeError: sequence item 0: expected str instance, QVariant found

Python version: 3.8.7 (default, Feb 10 2021, 09:04:08) [Clang 12.0.0 (clang-1200.0.32.29)] 
QGIS version: 3.16.15-Hannover Hannover, e7fdad6431

**Comment by juliepierson** [comment]
Hi Ryan,
Thanks for your input and sorry for the delay. I'm afraid this plugin is no longer maintained since the "Aggregate" function in the processing toolbox does the same job (and does it better !). Could you confirm to me that you can do what you want with this aggregate tool ? I can then remove this plugin from the QGIS repository, it will be clearer for QGIS users.
Thanks !

**Comment by ryanjshields** [comment]
Hey Julie! Yep you are spot on with the Aggregate to. Sorry this got buried in my inbox and I’m just doing a purge. Thanks for getting back to me!

Ryan Shields

**Comment by juliepierson** [comment]
Ok, no problem, thanks Ryan :-)
